[project]
name = "sc-genex"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "anndata>=0.13.2",
    "enformer-pytorch>=0.8.12",
    "h5py>=3.16.0",
    "numpy>=2.5.2",
    "pandas>=3.0.5",
    "pysam>=0.24.0",
    "scipy>=1.18.0",
    "torch>=2.13.0",
]
